name: Check

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  shell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: shellcheck module/*.sh module/bin/ql scripts/*.sh
      - run: python3 -m py_compile scripts/make-entrypoint.py

